name: CI/CD Pipeline

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: compile with maven
        run: mvn compile
      - name: Run tests
        run: mvn test
